#!/usr/bin/env bash
# TODO: Clean up the arguments here
CUDA_VISIBLE_DEVICES=0 python3.7 main.py --batch_size=16 \
                  --instruction_embedding_size 64 \
                  --encoder_hidden_size 64 \
                  --encoder_num_layers 1 \
                  --min_wordtype_occurrence=2 \
                  --full_observability=True \
                  --saved_game_dir="../mturk/games/data/" \
                  --game_file_suffixes "1_27" "2_2" "2_3" "junior2_3" \
                  --game_state_filename="preprocessed/game_states.pkl" \
                  --update_type=SUPERVISED \
                  --held_out_prop 0.05 \
                  --leader_steps_per_turn=5 \
                  --follower_steps_per_turn=10 \
                  --save_dir="experiments/" \
                  --experiment_name="finetune_aggregate_no_rnn_0" \
                  --optimizer=ADAM \
                  --initial_patience 10 \
                  --patience_update_ratio 1.01 \
                  --state_encoder_type=ALPHAGOZERO \
                  --dropout=0.0 \
                  --use_instructions=True \
                  --use_states=True \
                  --finetune_learning_rate=0.001 \
                  --rotate_features=False \
                  --rotate_environment=True \
                  --rotate_env_to_current_state=False \
                  --model_type=PATH_FROM_TRAJ_JOINT \
                  --property_embedding_size=32 \
                  --crop_size=5 \
                  --use_recurrence=False \
                  --use_instructions=False \
                  --use_timewise_distributions=False \
                  --output_seq_len=25 \
                  --end_to_end=True \
                  --encoder_stride=2 \
                  --num_image_channels=64 \
                  --lingunet_after_conv_channels=48 \
		          --conv_before_lingunet=False \
                  --lingunet_after_text_channels=24 \
		          --lingunet_conv_layers=2 \
                  --encoder_depth=4 \
                  --encoder_padding=1 \
                  --build_style=SUM \
                  --kernel_size=3 \
                  --dense_representation=True  \
                  --feature_size=16 \
                  --presence_channels=False \
                  --rotate_features=False \
                  --simplify_instructions=False \
                  --rotate_environment=True \
                  --traj_weight_by_time=True \
                  --rotate_env_to_current_state=False \
                  --num_output_hidden_layers=0 \
                  --conv_encode_map_distributions=True \
                  --finetune_auxiliary_coeff_hex_properties=0. \
                  --finetune_auxiliary_coeff_cards=1. \
                  --finetune_auxiliary_coeff_trajectory=1.\
                  --finetune_auxiliary_coeff_final_cards=1. \
                  --finetune_auxiliary_coeff_avoid_locs=0.1 \
                  --finetune_auxiliary_coeff_impassable_locs=0.1 \
                  --finetune_auxiliary_coeff_implicit=0.7 \
                  --use_impassable_locations=True \
                  --use_avoid_locations=True \
                  --use_trajectory=True \
                  --use_card_predictions=True \
                  --aggregate_examples=True \
                  --generate_new_cards=True \
                  --pretrained_hex_predictor_filepath="experiments/hex_all_0/model_6_bestacc.pt" \
                  --pretrained_generator_filepath="experiments/action_no_rnn_0/model_11_card.pt"
